### ISSUE TITLE
[Bug] TypeError: LlavaLlamaForCausalLM.forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by DylanLIiii** [apple/ml-slowfast-llava#1]
Reference Issues in llava https://github.com/haotian-liu/LLaVA/issues/1448

**Comment by xumingze0308** [comment]
Using a different version of transformers can solve this problem ([reference](https://github.com/huggingface/transformers/issues/29426#issuecomment-2028934210)).
`pip install transformers==4.37.2`

**Comment by xumingze0308** [comment]
Thanks! The bug was fixed.
